name       : seafile
version    : 6.2.11
release    : 15
source     :
    - https://github.com/haiwen/seafile/archive/v6.2.11.tar.gz : 58c751d0d5f7afa674718a08ed828e9f94d00173d721018bbf61dd6b032f5a57
license    :
    - GPL-2.0-only
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
