name       : seafile
version    : 6.0.7
release    : 3
source     :
    - https://github.com/haiwen/seafile/archive/v6.0.7.tar.gz : e563eade01330bf679f3e6b9f0202b198170cdd8ec80642d9fb670b3a5cda793
license    :
    - GPL-2.0
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libccnet)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
