name       : seafile
version    : 8.0.4
release    : 27
source     :
    - https://github.com/haiwen/seafile/archive/refs/tags/v8.0.4.tar.gz : 1c17cf589a2093f8d5423e56b2f6a098fdd44e8b7b9ffb62846270458aa0d197
license    :
    - GPL-2.0-only
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static --with-python3
build      : |
    %make
install    : |
    %make_install
