name       : seafile
version    : 7.0.1
release    : 16
source     :
    - https://github.com/haiwen/seafile/archive/v7.0.1.tar.gz : c79a186e3a512454cb65d863bd45ecc8ae2c66a0dd2010533f3fed7862fa92f8
license    :
    - GPL-2.0-only
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
