name       : seafile
version    : 6.1.5
release    : 8
source     :
    - https://github.com/haiwen/seafile/archive/v6.1.5.tar.gz : 19f9ccd515af8b4dc422479dfdc69ab3a55978751ed25653e0f5d04196949f6a
license    :
    - GPL-2.0
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libccnet)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
