name       : seafile
version    : 6.1.3
release    : 7
source     :
    - https://github.com/haiwen/seafile/archive/v6.1.3.tar.gz : bcd6e363dc3e1727b1cbf1c889724ffff6e4002c507745445d6fd623faf7d47e
license    :
    - GPL-2.0
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libccnet)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
